### PR TITLE
First pass at splitting out the unix-specific parts of this lib

### PR DESCRIPTION
**Pull request by raboof**
For review, there's probably a lot wrong with this approach, I'm here to learn :)

### CODE REVIEW

**Comment by raboof** [comment]
Not sure why travis is failing - seems to go wrong when installing opium_unix while it is already installed?

**Comment by raboof** [comment]
After these changes it still seems Opium pulls in some references to `Unix`: one in Core_kernel (https://github.com/janestreet/core_kernel/issues/42), but also:

```
ocamlbuild -use-ocamlfind -pkgs lwt.syntax,conduit.mirage,core_kernel,mirage-clock-xen,mirage-console.xen,mirage-http,mirage-net-xen,mirage-types.lwt,mirage.runtime,opium,re.str,tcpip.stack-direct -tags "syntax(camlp4o),annot,bin_annot,strict_sequence,principal" -tag-line "<static*.*>: -syntax(camlp4o)" -cflag -g -lflags -g,-linkpkg,-dontlink,unix main.native.o
+ ocamlfind ocamlopt -g -linkpkg -dontlink unix -output-obj -package tcpip.stack-direct -package re.str -package opium -package mirage.runtime -package mirage-types.lwt -package mirage-net-xen -package mirage-http -package mirage-console.xen -package mirage-clock-xen -package core_kernel -package conduit.mirage -package lwt.syntax -syntax camlp4o todobackend.cmx main.cmx -o main.native.o
File "_none_", line 1:
Error: No implementations provided for the following modules:
         Unix referenced from /home/aengelen/.opam/system/lib/lwt/lwt-unix.cmxa(Lwt_engine),
           /home/aengelen/.opam/system/lib/lwt/lwt-unix.cmxa(Lwt_unix),
           /home/aengelen/.opam/system/lib/lwt/lwt-unix.cmxa(Lwt_io),
           /home/aengelen/.opam/system/lib/lwt/lwt-unix.cmxa(Lwt_log)
Command exited with code 2.
```

How could I analyse how this dependency to `lwt-unix` is introduced?

**Comment by rgrinberg** [comment]
`cat $(ocamlfind query core_kernel)/META` gives me

```
# OASIS_START
# DO NOT EDIT (digest: 8efbc4931a910c194904e8a4904b8961)
version = "112.24.00"
description = "Jane Street Capital's standard library overlay"
requires =
"bin_prot custom_printf variantslib sexplib enumerate fieldslib bigarray pa_bench pa_ounit pa_test typerep_lib unix"
archive(byte) = "core_kernel.cma"
archive(byte, plugin) = "core_kernel.cma"
archive(native) = "core_kernel.cmxa"
archive(native, plugin) = "core_kernel.cmxs"
exists_if = "core_kernel.cma"
package "check_caml_modify" (
 version = "112.24.00"
 description = "Jane Street Capital's standard library overlay"
 requires = "pa_ounit"
 archive(byte) = "check_caml_modify.cma"
 archive(byte, plugin) = "check_caml_modify.cma"
 archive(native) = "check_caml_modify.cmxa"
 archive(native, plugin) = "check_caml_modify.cmxs"
 exists_if = "check_caml_modify.cma"
)
# OASIS_STOP
```

@avsm how come it still pulls in unix?

**Comment by raboof** [comment]
`Core_kernel` should no longer pull in `Unix` when https://github.com/janestreet/core_kernel/pull/45 is merged

**Comment by rgrinberg** [comment]
I wouldn't get my hopes up for a speedy reply for your core PR :)

I'll have a closer look at your PR on the weekend and will probably merge anyway. I needed an excuse to get rid of core anyway and this looks like it might be it.

**Comment by rgrinberg** [comment]
@raboof One year later and this has finally bee done. There's `opium_kernel` and `opium` for now (but I'm still not 100% sure about the names)

**Comment by raboof** [comment]
Wow how time flies :) - good to hear!

**Pull request closed without merging**
