### PR TITLE
Add odoc with-doc dependency

### PR DESCRIPTION
**Pull request by reynir**
Should enable us to `opam install --with-doc opium`.

### CODE REVIEW

**Comment by tmattio** [comment]
Thanks @reynir!

The dependencies are listed in `dune-project` and the `opam` files are generated by Dune. In addition, we use lock files for the CI, so we need to regenerate them when changing the dependencies (with `opam lock -y .`)

You'll probably want to add `odoc` to `rock` and `opium-testing` as well.

**Comment by reynir** [comment]
I added odoc {with-doc} in the proper place and for all packages.

`opam lock` does not seem to understand the `-y` flag, and without the diff is rather large. I did not commit that since I'm not sure it's right.

**Comment by tmattio** [comment]
I generated the lock files (the lock files you generated did not include test dependencies)

**Comment by tmattio** [comment]
Thank you @reynir 🎉

**Comment by reynir** [comment]
Do you know why they didn't? Anyway, thank you!

**Comment by tmattio** [comment]
I think they don't get generated if you didn't install them in you current switch (so you need to use `opam install` with `--with-test`)

**Pull request merged**
